#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
admin=$3
adminpass=$4
user=$5

# Check Wheezy or Jessie
DEB_VERSION=$(lsb_release -cs)

if [[ "$DEB_VERSION" != "wheezy" ]] && [[ "$DEB_VERSION" != "jessie" ]]; then
        echo "Tvheadend can only be install on Debian Wheezy or Jessie"
        exit 1
fi

# Check URL
sudo yunohost app checkurl $domain$path -a tvheadend
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Remove trailing "/" for next commands
path=${path%/}

# Check port availability
sudo yunohost app checkport 9981
if [[ ! $? -eq 0 ]]; then
  echo "Port 9981, for Tvheadend WebUI is not available."
  exit 1
fi
sudo yunohost app checkport 9982
if [[ ! $? -eq 0 ]]; then
  echo "Port 9982, for Tvheadend remote control is not available."
  exit 1
fi

# Open port in firewall
sudo yunohost firewall allow TCP 9981 > /dev/null 2>&1
sudo yunohost firewall allow TCP 9982 > /dev/null 2>&1

# Add Tvheadend repository
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
echo "deb https://dl.bintray.com/tvheadend/deb $DEB_VERSION release" | sudo tee /etc/apt/sources.list.d/tvheadend.list
sudo apt-get install apt-transport-https
sudo apt-get update
export DEBIAN_FRONTEND=noninteractive
sudo -E apt-get install tvheadend -y

# Manager Tvheadend service with Yunohost
sudo yunohost service add tvheadend

# Configure Nginx et all
credential=$(echo -n "$admin:$adminpass" | base64)
sed -i "s@ADMINNAME@$admin@g" ../conf/superuser
sed -i "s@ADMINPASSWORD@$adminpass@g" ../conf/superuser
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ADMINCREDENTIAL@$credential@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/tvheadend.conf
sudo cp ../conf/superuser /home/hts/.hts/tvheadend/superuser

# Remove acces to all users to remove tile
sudo yunohost app removeaccess tvheadend
sudo yunohost app addaccess tvheadend -u $user

# Reload or restart
sudo service tvheadend restart
sudo service nginx reload
sudo yunohost app ssowatconf

