#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

sudo yunohost app checkurl $domain$path -a tvheadend
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Remove trailing "/" for next commands
path=${path%/}

echo "deb http://apt.tvheadend.org/stable wheezy main"  | sudo tee /etc/apt/sources.list.d/tvheadend2.list
sudo apt-get update
sudo apt-get install tvheadend -y

# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/tvheadend.conf
sudo service tvheadend restart
sudo service nginx reload
sudo yunohost app ssowatconf

