#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check Wheezy or Jessie
DEB_VERSION=$(lsb_release -cs)

if [[ $DEB_VERSION != "wheezy" ]] && [[ $DEB_VERSION = "jessie" ]]; then
	echo "Tvheadend can only be install on Debian Wheezy or Jessie"
	exit 1
fi

# Check URL
sudo yunohost app checkurl $domain$path -a tvheadend
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Remove trailing "/" for next commands
path=${path%/}

# Check port availability
sudo yunohost app checkport 9981
if [[ ! $? -eq 0 ]]; then
  echo "Port 9981, for Tvheadend WebUI is not available."
  exit 1
fi
sudo yunohost app checkport 9982
if [[ ! $? -eq 0 ]]; then
  echo "Port 9982, for Tvheadend remote control is not available."
  exit 1
fi

# Open port in firewall
sudo yunohost firewall allow TCP 9981 > /dev/null 2>&1
sudo yunohost firewall allow TCP 9982 > /dev/null 2>&1


# Add Tvheadend repository
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61 
echo "deb https://dl.bintray.com/tvheadend/deb $DEB_VERSION" | sudo tee /etc/apt/sources.list.d/tvheadend.list
sudo apt-get update -qq
sudo apt-get install tvheadend -y

# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/tvheadend.conf
sudo service tvheadend restart
sudo service nginx reload
sudo yunohost app ssowatconf

